### PR TITLE
[SHARE-925][Feature] Allow case insensitive keyword search

### PR DESCRIPTION
**Pull request by laurenbarker**
## Purpose
Allow case insensitive search for sources.

## Changes
Add a normalizer for keywords.

## Side effects
Need to re-index everything.

### CODE REVIEW

**Comment by aaxelb** [comment]
Does using a normalizer like this mean the sources facet/donut will be all lower case?

**Comment by laurenbarker** [comment]
Ew. Yes it does.

**Comment by aaxelb** [comment]
Maybe we should add a `sources.exact` field for aggregations/filtering? Then once preprints/dashboard/whoever have switched over, `sources` could be `text`, which would be nicer for typed queries.

**Comment by laurenbarker** [comment]
That would probably make the most sense.

**Comment by laurenbarker** [comment]
@chrisseto would you be okay with splitting the case insensitive search stuff into two releases? One for adding an exact field for sources and another for making the sources field a text field. It would probably be easier than coordinating a release with preprints and the dashboard.

**Comment by chrisseto** [comment]
Would it make more sense to use an [analyzer/tokenizer](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-analyzer.html) given that they are officially supported?

**Comment by laurenbarker** [comment]
@chrisseto, analyzer/tokenizer can't be used on a [keyword field](https://www.elastic.co/guide/en/elasticsearch/reference/5.4/keyword.html)
> Keyword fields are only searchable by their exact value.

So are you saying your on board with switching to a text field or am I missing something?

**Comment by chrisseto** [comment]
@laurenbarker Do you remember what the final decision on this was?

**Comment by laurenbarker** [comment]
@chrisseto, we still haven't heard back from product on this one. I would say move it out of the sprint and close the PR until a decision is made.

**Comment by chrisseto** [comment]
@laurenbarker alright, thank you!

**Pull request closed without merging**
