### PR TITLE
Update urls to v2

### PR DESCRIPTION
**Pull request by leb2dg**
Should be merged in conjunction with: https://github.com/CenterForOpenScience/ember-share/pull/110

* Updated url on OSF

### CODE REVIEW

**Comment by chrisseto** [comment]
Couldn't you just change the root url in `project/urls`?

```python
    url(r'^api/', include('api.urls', namespace='api')),
```

**Comment by leb2dg** [comment]
Ahh I figured there was a better way. Will change 👍

**Comment by leb2dg** [comment]
@chrisseto, the API changes are ready for review/testing 💸

**Comment by chrisseto** [comment]
And throwing a deployment note here. Preprints relies on the API without the v2. We'll have to coordinate releasing the two.

**Comment by chrisseto** [comment]
Actually, it might make more sense to just throw a redirect in the django app. That way we can just redirect `/api/(?!v\d+)/` to the latest api version.

**Comment by leb2dg** [comment]
Will that work with differentiating between v1 and v2 urls?

**Comment by chrisseto** [comment]
It should. Just match all api urls that don't have `vsomething` directly after the `/api/` bit

**Comment by leb2dg** [comment]
Oh nice, I'll add that then

**Pull request merged**
