### PR TITLE
[SHARE-529][SHARE-590][Feature] Use cursor, not offset, in Crossref harvester.

### PR DESCRIPTION
**Pull request by aaxelb**
So it doesn't break when harvesting more than 10k records.

Also, keep only a list of RawData IDs when harvesting, not all the RawData instances.

https://openscience.atlassian.net/browse/SHARE-529
https://openscience.atlassian.net/browse/SHARE-590

### CODE REVIEW

**Comment by chrisseto** [comment]
@aaxelb any concern with eating too much memory here? All the docs will end up being held in memory.

**Comment by aaxelb** [comment]
@chrisseto Yes, [I made a ticket for it](https://openscience.atlassian.net/browse/SHARE-590), though I wasn't sure if it was a big enough issue to fix right now. I could definitely add that to this PR, though.

**Comment by chrisseto** [comment]
@aaxelb Could you go ahead and throw that in here? Running out of memory will affect more just this task.

**Comment by aaxelb** [comment]
@chrisseto 👍

**Pull request merged**
