### PR TITLE
feature/adding-favicons-to-provider-directories

### PR DESCRIPTION
**Pull request by SSJohns**
Will pull together all the files from the static directories in the system and put them in one place.

Should not have any ill effects as it is not modifying current files. Although access of the favicons will greatly depend on the file structure provided by the script in the other PR.
#291

### CODE REVIEW

**Comment by SSJohns** [comment]
@chrisseto Ready to review.

**Comment by chrisseto** [comment]
You should be able to just but files in `/static/img/..` for each provider. Django *should* be namespacing static files.
The section right above [this one](https://docs.djangoproject.com/en/1.9/howto/static-files/#serving-static-files-during-development) has some details on how to do it.

**Comment by SSJohns** [comment]
I'm sorry what do you mean? When you run `python manage.py collectstatic` it grabs all of these files and puts them into the root directory that you are talking about. That's why I had the script, it grabbed all the favicons and put them into the folders and the above command relocated them all to one place.

**Comment by chrisseto** [comment]
Right now the all the static folder structures look like `/static/ca.lwbin/...`. Using django there should be a way to have each individual provider just store files like `/static/img/...` and have `collectstatic` namespace them, so the final static directory will look like `/static/ca.lwbin/...`

Could you also remove the favicon folder? `img/favicon.ico` is fine.

**Comment by SSJohns** [comment]
You asked me to put in the favicon folder.... So let me get this straight before I go ahead.

You want in each folder named `/provider/edu/calpoly` you want a folder called `static/img` and the favicon.ico in that folder. Then when you pull it together with Django you want Django to name it `static/<providerappname>/img/favicon.ico`. Is that right or am I missing something?

**Comment by chrisseto** [comment]
Spot on

**Comment by SSJohns** [comment]
I think my folder structure the first time was right, there is no django way to do autonamespacing. The tutorials suggest to make another directory in your app like `/static/<providerappname>/img/etc.ico`.

**Comment by chrisseto** [comment]
Whoops, looks like I misread the documentation. It's ridiculous that they don't do that automatically.

**Comment by SSJohns** [comment]
Okay that should be everything @ chrisseto

**Comment by chrisseto** [comment]
Beautiful, sorry for the confusion!

**Pull request merged**
