### PR TITLE
feature/favicons-directory-script

### PR DESCRIPTION
**Pull request by SSJohns**
A script to crawl the directories and make a static file and place the ico into that directory. Not sure if I can get a custom name for the ones here. So far the only ones I got were badly named and wouldn't render, probably because the name I pulled wasn't right.

Addition for #291 not necessary, but it helps when adding many harvesters. Checked for consistency, of the ~160 places harvested from it pulled 41 wrong icons. Mixed into that 41 were updates to the favicon from the company and smaller versions of the same icon. All icons added in #311

### CODE REVIEW

**Comment by chrisseto** [comment]
Please follow git flow naming conventions http://nvie.com/posts/a-successful-git-branching-model/

**Comment by SSJohns** [comment]
@chrisseto What's wrong with the name of this one?

**Comment by chrisseto** [comment]
@SSJohns Read the article

**Comment by SSJohns** [comment]
@chrisseto Yeah I read it again, just now. I also read it at the beginning of the summer when Brian referred it to me. Is it the improvement naming convention? I've been using that all summer and no one complained as of yet. If that's not cool, could you let me know, I'm really not sure what specifically you didn't like about the naming.

**Comment by chrisseto** [comment]
There are only `feature/*`, `hotfix/*`, and `release/*` branches.
If you intend for your branch to be merged into develop it's a `feature/*` branch, if you intend for it to be merged into master it's a `hotfix/*`

**Comment by SSJohns** [comment]
Okay that makes sense. Thanks, I had figured that the `improvements/*` branch was fine since no one said other wise. Thanks for letting me know.

**Comment by chrisseto** [comment]
Closing in favor of https://github.com/CenterForOpenScience/SHARE/pull/311

**Pull request closed without merging**
