### PR TITLE
[SHARE-470][Feature] Bleach html for elastic & graphql description

### PR DESCRIPTION
**Pull request by leb2dg**
## Purpose

Bleach description so that it can be rendered safely.

## Changes

* Bleach description returned by elastic
* Bleach description returned by graphql

## Side effects
None

## Ticket
https://openscience.atlassian.net/browse/SHARE-470

### CODE REVIEW

**Comment by chrisseto** [comment]
Could you throw a couple unittests in that just bleach a couple strings? For peace of mind and just in case something changes if we updated bleach?

I'm a bit uneasy about allowing hyperlinks. Let's go ahead and strip them for the moment.

```html
<p class="Something-that-may-or-may-not-exist" style="size: large;">Horribly styled text</p>
<!-- Should become -->
<p>Horribly styled text</p>


<a href="http://MyEvilSite.io/">Click me for puppies</a>
<!-- Should become -->
Click me for puppies
```

**Comment by chrisseto** [comment]
Could you throw in one more test to make sure that styles and classes are stripped?
Actually I don't thing there are any attributes that we'd want set

```html
<i style="size: xxl; color: orange;" class="geocities-i" data-bind="ko: bestCities">GeoCities was best cities</i>
<!-- Should become -->
<i>GeoCities was best cities</i>
```

**Comment by leb2dg** [comment]
## Default bleach setting:

#### Tags

```
>>> bleach.ALLOWED_TAGS
['a', 'abbr', 'acronym', 'b', 'blockquote', 'code', 'em', 'i', 'li', 'ol', 'strong', 'ul']
```

#### Attributes

```
>>> bleach.ALLOWED_ATTRIBUTES
{'abbr': ['title'], 'acronym': ['title'], 'a': ['href', 'title']}
```

#### Styles

```
>>> bleach.ALLOWED_STYLES
[]
```

#### Protocols

this might be why tests are passing
```
>>> bleach.ALLOWED_PROTOCOLS
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'bleach' has no attribute 'ALLOWED_PROTOCOLS'
```
from [source code](https://github.com/mozilla/bleach/blob/70b1d2d03a069791a19ab6291b6e885371f6fe0f/bleach/__init__.py#L44)
```
ALLOWED_PROTOCOLS = ['http', 'https', 'mailto']
```

**Comment by chrisseto** [comment]
👍

**Pull request merged**
